//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabComputoWeb.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaboratoriosDB : DbContext
    {
        public LaboratoriosDB()
            : base("name=LaboratoriosDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAccesoAlumno> tblAccesoAlumnoes { get; set; }
        public virtual DbSet<tblAlumno> tblAlumnoes { get; set; }
        public virtual DbSet<tblClase> tblClases { get; set; }
        public virtual DbSet<tblComputadora> tblComputadoras { get; set; }
        public virtual DbSet<tblLaboratorio> tblLaboratorios { get; set; }
        public virtual DbSet<tblObjetosOlvidado> tblObjetosOlvidado { get; set; }
        public virtual DbSet<tblProfesor> tblProfesors { get; set; }
        public virtual DbSet<tblUsuario> tblUsuarios { get; set; }
    }
}
