//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabComputoWeb.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAlumno()
        {
            this.tblAccesoAlumnoes = new HashSet<tblAccesoAlumno>();
        }
    
        public int AlumnoID { get; set; }
        public string Nombre { get; set; }
        public string NumeroControl { get; set; }
        public string Correo { get; set; }
        public string Carrera { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
        public Nullable<decimal> Telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccesoAlumno> tblAccesoAlumnoes { get; set; }
    }
}
