//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabComputoWeb.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComputadora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblComputadora()
        {
            this.tblAccesoAlumnoes = new HashSet<tblAccesoAlumno>();
        }
    
        public int ComputadoraID { get; set; }
        public Nullable<int> LaboratorioID { get; set; }
        public int NumeroComputadora { get; set; }
        public bool Funciona { get; set; }
        public string Nota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccesoAlumno> tblAccesoAlumnoes { get; set; }
        public virtual tblLaboratorio tblLaboratorio { get; set; }
    }
}
