//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabComputoWeb.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClase
    {
        public int ClaseID { get; set; }
        public Nullable<int> LaboratorioID { get; set; }
        public Nullable<int> ProfesorID { get; set; }
        public System.DateTime FechaApartado { get; set; }
        public Nullable<bool> Registro { get; set; }
    
        public virtual tblLaboratorio tblLaboratorio { get; set; }
        public virtual tblProfesor tblProfesor { get; set; }
    }
}
