//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabComputoWeb.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLaboratorio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLaboratorio()
        {
            this.tblClases = new HashSet<tblClase>();
            this.tblComputadoras = new HashSet<tblComputadora>();
            this.tblObjetosOlvidado = new HashSet<tblObjetosOlvidado>();
        }
    
        public int LaboratorioID { get; set; }
        public string Nombre { get; set; }
        public int Capacidad { get; set; }
        public string Edificio { get; set; }
        public bool Disponible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClase> tblClases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblComputadora> tblComputadoras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblObjetosOlvidado> tblObjetosOlvidado { get; set; }
    }
}
