//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabComputoWeb.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblObjetosOlvidado
    {
        public int ObjetosOlvidadosID { get; set; }
        public int LaboratorioID { get; set; }
        public string Nombre { get; set; }
        public byte[] Foto { get; set; }
        public string Nota { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual tblLaboratorio tblLaboratorio { get; set; }
    }
}
